# Generated by Django 3.2.14 on 2022-08-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODOnotes', '0005_project_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(help_text='Required. 150 characters or fewer. ASCII letters and digits only.', max_length=150, verbose_name='username'),
        ),
    ]
